import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Provider as ChakraProvider } from '@/providers/ChakraProvider';
import {
  Box,
  Flex,
} from '@chakra-ui/react';
import Sidebar from '@/components/Sidebar';
import Navigation from '@/components/Navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <Navigation />
          <Flex>
            <Sidebar />
            <Box
              position={{ base: 'absolute', md: 'unset' }}
              w={{ base: 'calc(100% - 3.8rem)', md: '100%' }}
              ml={{ base: '3.8rem', md: 0 }}
            >
              {children}
            </Box>
          </Flex>
        </ChakraProvider>
      </body>
    </html >
  );
};
